version: '3.4'

services:
  projetoliteracriticofinal:
    image: rubensdnascimento/projetoliteracriticofinal
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    links:
     - mongodb
  mongodb:
    image: mongo:latest
    ports:
     - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: